README.md

fix: typo on readme

---

docs/reference/intro.md

Added summary to intro docs.
Direct link to new content in preview: https://deploy-preview-24--lucky-creponne-baf9b3.netlify.app/docs/reference/intro/

Enhance intro doc

---

docs/reference/evaluation-api/_category_.json
docs/reference/evaluation-api/evaluation-api.mdx
docs/reference/hooks/hooks.mdx
docs/reference/intro.md
sidebars.js

Adding hooks doc, removing extraneous files.
Direct preview link to new content: https://deploy-preview-30--lucky-creponne-baf9b3.netlify.app/docs/reference/hooks/
Closes: https://github.com/open-feature/docs.openfeature.dev/issues/22

Add hooks doc

---

src/pages/index.tsx

update home page description

---

src/plugins/external-content.js
src/plugins/update-git-submodule.js

update external content once

---

package.json
yarn.lock

upgrade docusaurus to v2 ga

---

src/pages/index.module.css

set hero banner background to black

---

README.md

update deployment information

---

docs/reference/contributing.md

Document how to contribute.

---

LICENSE
LICENSE-CODE
README.md

add license information

---

.eslintrc.json
docs/reference/intro.mdx
docs/reference/sdks.mdx
package.json
src/components/custom/SDKComponentCard/index.tsx
src/components/custom/SDKComponentCard/styles.module.css
src/components/custom/SDKComponentTable/index.tsx
src/components/custom/index.ts
yarn.lock

- Adds SDK card component
- Adds SDK card table and new page
Direct link to new content in preview: https://deploy-preview-60--lucky-creponne-baf9b3.netlify.app/docs/reference/sdks

Add SDK table

---

docs/reference/concepts/02-provider.mdx

Add double method on Java provider example

---

src/components/HomepageFeatures/index.tsx

Not my favorite here, but hopefully it'll start a conversation.
Refs #6

Link off to javadoc

---

docusaurus.config.js
package.json
yarn.lock

replace local search library

---

src/components/TechnologiesFeatures/JavaFeatures/index.tsx

feat: add flagd provider card

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documenation.yaml
.github/ISSUE_TEMPLATE/document-hook.yaml
.github/ISSUE_TEMPLATE/document-provider.yaml
.github/ISSUE_TEMPLATE/feature.yaml
.github/ISSUE_TEMPLATE/register-provider.yaml
CODEOWNERS

Add the following issue templates:
- Bug
- Documentation
- Feature
- Add Hook
- Add Provider

Add GitHub Issue Templates

---

docs/reference/concepts/02-provider.mdx
package.json
src/components/custom/CopyChecklist/index.tsx
src/components/custom/CopyChecklist/styles.module.css
src/components/custom/index.ts
yarn.lock

- Adds provider checklist and FAQ
- Adds md checklist component that allows you to copy rendered checklist as raw markdown.
see: https://deploy-preview-96--lucky-creponne-baf9b3.netlify.app/docs/reference/concepts/provider#checklist

feat: add provider checklist

---

blog/02-09-2022-configuring-a-logger-for-the-go-sdk.mdx
blog/02-09-2022-creating-a-provider-for-the-go-sdk.mdx
blog/26-08-2022-creating-a-hook-for-the-go-sdk.mdx
docs/reference/technologies/go.mdx
docs/reference/technologies/golang.mdx
src/components/HomepageFeatures/index.tsx
src/components/TechnologiesFeatures/GoFeatures/index.tsx
src/components/TechnologiesFeatures/index.ts
src/components/TechnologiesFeatures/technologies-table.tsx
yarn.lock

Signed-off-by: Skye Gill <gill.skye95@gmail.com>

replace golang-sdk & golang-sdk-contrib with go-sdk & go-sdk-contrib

---

docs/reference/concepts/02-provider.mdx
src/components/HomepageFeatures/index.tsx

Update dotnet examples inline with version 0.2.3
https://github.com/open-feature/dotnet-sdk/pull/62

fix!: update dotnet namespace to OpenFeatureSDK

---

src/components/TechnologiesFeatures/JavascriptFeatures/index.tsx

chore: update split js provider url

---

blog/02-09-2022-configuring-a-logger-for-the-go-sdk.mdx
blog/02-09-2022-creating-a-provider-for-the-go-sdk.mdx
blog/26-08-2022-creating-a-hook-for-the-go-sdk.mdx
docs/reference/concepts/01-evaluation-api.mdx
docs/reference/concepts/03-evaluation-context.mdx
docs/reference/concepts/04-hooks.mdx
src/components/HomepageFeatures/index.tsx

Signed-off-by: Skye Gill <gill.skye95@gmail.com>

update go-sdk client api calls to be inline with current state

---

blog/02-09-2022-creating-a-provider-for-the-go-sdk.mdx
blog/26-08-2022-creating-a-hook-for-the-go-sdk.mdx

Signed-off-by: Skye Gill <gill.skye95@gmail.com>

update creating provider for the go-sdk blog to be inline with go-sdk@v0.5.0

---

docs/reference/concepts/01-evaluation-api.mdx

update evaluation details table to comply with spec v0.5.0

---

blog/02-09-2022-configuring-a-logger-for-the-go-sdk.mdx
blog/02-09-2022-creating-a-provider-for-the-go-sdk.mdx
docs/reference/concepts/03-evaluation-context.mdx

- brings inline with [go-sdk@v0.6.0 - (awaiting release)](https://github.com/open-feature/go-sdk/pull/95)
Fixes https://github.com/open-feature/docs.openfeature.dev/issues/136

update docs to be inline with go-sdk@v0.6.0

---

docs/reference/concepts/01-evaluation-api.mdx
docs/reference/concepts/03-evaluation-context.mdx
docs/reference/concepts/04-hooks.mdx

Update c# code samples to match latest SDK changes.

chore: update dotnet examples

---

src/components/ServerTechnologiesFeatures/GoFeatures/index.tsx
static/img/check-circle-no-fill.svg

Added available Go hooks to list of hooks
Fixes #161

chore: include OpenTelemetry and Validation hooks in list of Go hooks

---

docs/reference/concepts/02-provider.mdx

Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>
small improvements to documentation

docs: small improvements

---

docs/reference/concepts/03-evaluation-context.mdx

Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>
correction typo

docs: typo

---

docs/reference/concepts/01-evaluation-api.mdx

Signed-off-by: David Hirsch <david.hirsch@dynatrace.com>
fixes small typos in the documentation

docs: correction small typos

---

src/components/ClientTechnologiesFeatures/WebFeatures/index.tsx
src/components/ServerTechnologiesFeatures/DotnetFeatures/index.tsx
src/components/ServerTechnologiesFeatures/GoFeatures/index.tsx
src/components/ServerTechnologiesFeatures/JavaFeatures/index.tsx
src/components/ServerTechnologiesFeatures/JavascriptFeatures/index.tsx

Correct capitalisation of CloudBees

docs: Capitalisation of CloudBees

---

docs/reference/concepts/02-provider.mdx
src/components/HomepageFeatures/index.tsx

Signed-off-by: Todd Baert <toddbaert@gmail.com>

fix: update outdated dotnet examples

---

src/components/ServerTechnologiesFeatures/DotnetFeatures/index.tsx

Add Split .NET provider

---

docs/tutorials/ofo.md

Signed-off-by: Kavindu Dodanduwa <kavindudodanduwa@gmail.com>
Fixes incorrect namespace references in the K8s commands along with other minor correction

fix: namespace of the deployment

---

docs/getting-started/node.md

- adds a Getting Started walk through for Node.JS

Add initial node getting started doc

---

docs/getting-started/java.md

PR introduces getting started documentation for OpenFeature Java SDK
Given that this is a getting started guide, you should be able to validate content by following the given steps in it.

feat: Initial version of Java getting started page

---

src/components/ServerTechnologiesFeatures/DotnetFeatures/index.tsx

fix: dotnet artifact link

---

docs/tutorials/getting-started/node.mdx

Change express.js to express

---

src/components/ClientTechnologiesFeatures/WebFeatures/index.tsx

add client side split provider

---

src/components/ServerTechnologiesFeatures/DotnetFeatures/index.tsx

Closes: https://github.com/open-feature/docs.openfeature.dev/issues/202
Direct link to preview: https://deploy-preview-203--lucky-creponne-baf9b3.netlify.app/docs/reference/technologies/server/dotnet

doc: add dotnet goff

---

docs/reference/concepts/03-evaluation-context.mdx

Update client context .NET example

---

docs/reference/concepts/03-evaluation-context.mdx

Update context setting examples for JS

---

docs/tutorials/getting-started/node.mdx
src/components/custom/tutorial/flagd-content.mdx

Direct link: https://deploy-preview-219--lucky-creponne-baf9b3.netlify.app/docs/tutorials/getting-started/node

Add JS getting started example

---

docs/tutorials/getting-started/node.mdx
src/components/custom/tutorial/flagd-content.mdx

- updates flagd configuration doc link 
- fixes example start command

docs: Flagd doc update

---

docs/reference/concepts/01-evaluation-api.mdx
docs/reference/concepts/03-evaluation-context.mdx
docs/reference/concepts/04-hooks.mdx

- fix the method calling operators in PHP snippets

docs: fix method call operators in PHP snippets

---

src/components/ServerTechnologiesFeatures/JavaFeatures/index.tsx

doc: add java otel hook

---

src/components/ServerTechnologiesFeatures/PhpFeatures/index.tsx

- add Validators hooks for PHP
Check out the preview site under PHP.

docs: add Validators hooks for PHP

---

docs/tutorials/getting-started/go.mdx
package.json
yarn.lock

Introduce Go getting started guide. 
Fixes #208

feat: Add Go Getting started guide

---

src/components/custom/tutorial/flagd-change-content.mdx
src/components/custom/tutorial/flagd-content.mdx

Signed-off-by: James Milligan <james@omnant.co.uk>
- update flag configuration file paths to conform with schema store regex

docs: update flagd filepath

---

renovate.json

- Configures renovate to upgrade dependencies in tutorials.
Fixes #260 
I've tested that this works as expected in my forked repo.

chore: renovate tutorial dependencies

---

blog/06-02-2023-catering-to-the-client-side.md

fix: typos in client-side blog

---

blog/26-08-2022-creating-a-hook-for-the-go-sdk.mdx
docs/reference/concepts/04-hooks.mdx
src/components/HomepageFeatures/index.tsx

- Absorbs Go Hook API changes (https://github.com/open-feature/go-sdk/pull/163)

docs: absorbed Go Hook API changes

---

src/components/HomepageFeatures/index.tsx

Updates the interface name of the provider as per the latest java-sdk

Updated interfaces of JavaSDK example as per latest version
